spring: 
  application:
    name: TestProject
  profiles: 
    active: test

eureka: 
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance: 
    prefer-ip-address: true

server:
  port: 8102
  context-path: /test
  max-http-header-size: 8192
  tomcat:
    accept-count: 2000
    max-connections: 20000
    max-threads: 2000
    uri-encoding: UTF-8
    min-spare-threads: 200
    accesslog:
      directory: /data/logs/
      enabled: false